AWSTemplateFormatVersion : '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: A simple Hello World Serverless project
Resources:
    Function:
        Type: AWS::Serverless::Function
        FunctionName: !Sub "${AWS::StackName}-GolangSkeleton"
        Properties:
            Runtime: go1.x
            Handler: main
            CodeUri: .
            Timeout: 30
        Policies:
            - AWSLambdaBasicExecutionRole
            - AmazonDynamoDBFullAccess
            - AWSXrayWriteOnlyAccess        
